### ISSUE TITLE
Possible nil pointer derefence on syslog.New failure

### ISSUE THREAD

**Issue by detaoin** [exoscale/exoip#17]
I was curious on how the logger was implemented, and by going through the code I stumbled upon this minor issue.

At https://github.com/exoscale/exoip/blob/b667cff1a1b624d8e12f2d93417adf2d209abcd4/logging.go#L48
`AssertSuccess` will call Logger.Crit on a nil Logger in case of non-nil error.

This simply means that the error message written to stderr is a little more cryptic than wanted if the connection to the system log daemon fails :-).

**Comment by greut** [comment]
Good catch!
