### ISSUE TITLE
Versioning of exoip image

### ISSUE THREAD

**Issue by FaKod** [exoscale/exoip#5]
Hi guys, the image on docker hub is last updated 4 days. 
However, I cannot see a code change. Additionally there are tags on the Git Repo but none at docker hub.
Can we have some versioning here (tags an Github)? Or do you expect to build the images by our own?

best Christopher

**Comment by retrack** [comment]
Hello,

We have linked builds from the github repo to the Docker Hub. In the future, builds will only be triggered upon code changes here.

Hope that helps.

**Comment by FaKod** [comment]
and an image tag 0.3.2 would be nice :-)

**Comment by FaKod** [comment]
So, you've changed the latest tag recently that breaks current installations.
Would be nice to have a version tag.....

**Comment by greut** [comment]
@FaKod I'm very sorry mate for breaking it. There is a tag for the version you've used to use. `exoscale/exoip:0.3.3`. The `0.3.2` was tagged before the Dockerfile was added.

https://hub.docker.com/r/exoscale/exoip/tags/
