### ISSUE TITLE
list of peers remains until exoip restart

### ISSUE THREAD

**Issue by FaKod** [exoscale/exoip#6]
UseCase:
Running an Exoip Pod in a Kubernetes Cluster

The exoip pod gets started on Cluster startup. Every exoip instance stores its peers, related to the given security group. OK, so far. But if I create an additional cluster node afterwards, peers do not get updated on the initial nodes. So no one will recognize if the new node dies again. 
This is an issue for dynamically created nodes.

So peers should get updated more frequently than on startup.

**Comment by greut** [comment]
The first step would be to store the security group / query that could repopulate the `Peers`

```go
// Engine
type Engine struct {
    ....
    Peers         []*Peer
    SecurityGroup *egoscale.SecurityGroup
}
```

**Comment by greut** [comment]
done in #13
