### ISSUE TITLE
no resilience on network issues

### ISSUE THREAD

**Issue by FaKod** [exoscale/exoip#7]
UseCase:
Running an Exoip Pod in a Kubernetes Cluster. All exoip Container default priority.

exoip removes peer Nics if it fails to connect the node. If the node that could not be connected  (in case of a network issue or ACL misconfiguration) is still alive, no one re-adds the Nic again.

**Comment by FaKod** [comment]
We are currently testing this simple solution: https://github.com/FaKod/exoip/blob/cs_wip_make_it_work/src/exoip/state.go#L20

It calles ObtainNic every 30s (configurable)

**Comment by FaKod** [comment]
OK, since this runs every 30 seconds on 7 Nodes and 4 Clusters, this leads to some traffic on the Exoscale API.

Thats why I'm testing this now: https://github.com/FaKod/exoip-k8s

It uses Kubernetes Simple Leader Election... this may be a solution.

**Comment by marcaurele** [comment]
That's still not acceptable for the API calls. You should get the VM's nic and only add the EIP if it's missing.

**Comment by greut** [comment]
digging old issues here.

Having a master node unsubscribing other ones seems okay. If they cannot communicate directly, you've got another issue. The `addIpToNic` in a `while` loop feels wrong.
