### ISSUE TITLE
Support netplan

### ISSUE THREAD

**Issue by ghost** [exoscale/exoip#70]
We have received a request that ExoIP does not work properly with Ubuntu 18.04 due to the switch to netplan. Can we implement support for that?

**Comment by pyr** [comment]
Netplan has decided to not support running arbitrary commands, as such there can be no direct reference to exoip from it. The recommended approach (as per https://netplan.io/faq#use-pre-up-post-up-etc-hook-scripts) is to use systemd's networkd-dispatcher functionality to create systemd units which wait for the network interfaces to be configured.
